[versions]
kotlin = "1.8.10"
compose = "1.4.3"
kotest = "5.5.5"


[bundles]
compose = [
    "compose-activity",
    "compose-material",
    "compose-material-icons",
    "compose-navigation",
    "compose-tabler-icons",
]

[libraries]
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2023.01.00" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.6.1" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-material-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.5.3" }
compose-tabler-icons = "br.com.devsrsouza.compose.icons.android:tabler-icons:1.0.0"
compose-ui-test = { module = "androidx.compose.ui:ui-test" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

[plugins]